services:
  pythonapp:
    image: "python:3.10.6-slim"
    command: bash -c 'while !</dev/tcp/mysql/3306; do sleep 1; done; pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0'    
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8009:8000
    volumes:
      - ".:/app"
    working_dir: "/app"
  
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: flutter
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
