services:
  pythonapp:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8009:8000
  
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: flutter
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
